name: Build Winlator APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Make gradlew executable
        working-directory: ./app
        run: chmod +x ./gradlew

      # НОВЫЙ ШАГ: Устанавливаем нужную версию CMake через Android SDK Manager
      - name: Install CMake 3.22.1
        run: echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "cmake;3.22.1"

      - name: Build APK (Debug)
        working-directory: ./app
        run: ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: winlator-custom-debug
          path: app/app/build/outputs/apk/debug/*.apk
